A total makeover to avoide many breakage conditions  	modified:   Dockerfile  	modified:   bin/my_init  	modified:   system_services.sh

diff --git a/bin/my_init b/bin/my_init
--- a/bin/my_init
+++ b/bin/my_init
@@ -11,7 +11,7 @@ runsvdir_PID=
 
 # functions
 
-# importing the environment variables form image
+# importing the environment variables from image
 import_envvars () {
 
  clear_existing_environment=${1:-true}
@@ -27,14 +27,14 @@ import_envvars () {
  done
 }
 
-# exporting the environment variable to the image
+# exporting the environment variables to the image
 export_envvars () {
  to_dir=${1:-true}
  no_record="HOME USER GROUP UID GID SHELL SHLVL PWD"
- # to begin .json and .sh file
+ # to begin .json and.sh files
   echo -n "{" > /etc/container_environment.json
   echo -n "" > /etc/container_environment.sh
- # saving variables into file. individual file by variable.
+  # saving variables into file. individual file by variable.
  env | while read -r line
  do
   a=`expr index "$line" \=`
@@ -45,7 +45,7 @@ export_envvars () {
   then
    continue
   else
-   # write to files
+    # write to files
     if [ $to_dir = true ] ; then echo $file_val > /etc/container_environment/$file_name ; fi
    # write to .sh file
     echo "export"  $file_name"='"$file_val"'" >> /etc/container_environment.sh
@@ -114,12 +114,56 @@ shutdown_runit_services() {
 
 # message to echo things to user
 message () {
-  echo "starting my_init.d"
+  echo "usage: my_init [-h|--help] [--skip-startup-files] [--skip-runit] [-- MAIN_COMMAND ]"
+  echo "optional arguments:"
+  echo "  -h, --help            show this help message and exit"
+  echo "  --skip-startup-files  Skip running /etc/my_init.d/* and /etc/rc.local"
+  echo "  --skip-runit          Do not run runit services"
+  echo "  --quiet               Only print warnings and errors"
 }
 
 # import & export env
 import_envvars false false
 export_envvars
+
+
+# condition for --help
+if [ `echo $temp_var | grep -c "\-\-help" ` -gt 0 ] || [ `echo $temp_var | grep -c "\-h" ` -gt 0 ] ; then
+  message
+  exit 0
+fi
+
+# condition for --quiet
+if ! [ `echo $temp_var | grep -c "\-\-quiet" ` -gt 0 ] ; then
+   :
+ else
+   temp_var=$(echo $temp_var|sed "s/--quiet//")
+   echo "--quiet still need to be implememted"
+fi
+
+# condition for --skip-startup-files
+if ! [ `echo $temp_var | grep -c "\-\-skip-startup-files" ` -gt 0 ] ; then
+   run_startup_files
+ else
+   temp_var=$(echo $temp_var|sed "s/--skip-startup-files//")
+fi
+
+# condition for --skip-runit
+if ! [ `echo $temp_var | grep -c "\-\-skip-runit" ` -gt 0 ] ; then
+   start_runit
+ else
+   temp_var=$(echo $temp_var|sed "s/--skip-runit//")
+   if  [ `echo $temp_var | grep -c "\-\- " ` -gt 0 ] ; then
+     temp_var=$(echo $temp_var|sed "s/--//")
+     exec $temp_var
+     exit 0
+    else
+      echo "Need to add command to do something:  -- command"
+      echo
+      message
+      exit 0
+   fi
+fi
 
 if  [ `echo $temp_var | grep -c "\-\- " ` -gt 0 ] ; then
 temp_var=$(echo $temp_var|sed "s/--//")
